#ifndef _JOYPAD_MBEDTLS_CONFIG_H
#define _JOYPAD_MBEDTLS_CONFIG_H

// 只保留最基础，完全关闭 TLS/SSL/加密栈
#define MBEDTLS_SHA256_C

// 关闭所有你不需要的东西
#undef MBEDTLS_MD_C
#undef MBEDTLS_ECDSA_C
#undef MBEDTLS_ENTROPY_C
#undef MBEDTLS_GCM_C
#undef MBEDTLS_PK_C
#undef MBEDTLS_PK_PARSE_C
#undef MBEDTLS_SSL_TLS_C
#undef MBEDTLS_SSL_CLI_C
#undef MBEDTLS_SSL_SRV_C
#undef MBEDTLS_TLS_CLIENT
#undef MBEDTLS_TLS_SERVER
#undef MBEDTLS_X509_USE_C
#undef MBEDTLS_X509_CRT_PARSE_C
#undef MBEDTLS_AES_C
#undef MBEDTLS_CIPHER_C
#undef MBEDTLS_BIGNUM_C
#undef MBEDTLS_OID_C
#undef MBEDTLS_ASN1_PARSE_C

// 禁用 Pico 硬件 SHA256 加速（避免报错）
#undef MBEDTLS_SHA256_ALT

#endif
